{% set name = "tty-color" %}
{% set version = "0.6.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 6f9c37ca3a4e2367fb2e6d09722762647d6f455c111f05b59f35730eeb24332a

build:
  noarch: generic
  number: 0
  script:
    - gem install --norc -l -V --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.txt
  summary: Terminal color capabilities detection
  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/piotrmurach/tty-color

extra:
  recipe-maintainers:
    - sodre
    - mwilson8
    - rluria14
