travis:
  secure:
    BINSTAR_TOKEN: xgqrVIf4Dxcrugop48o5ec3KHaFX1KPWngbZaPzyFST/VeaEiknwTYzit2Gaz3TH3/VwSwBF8NU7H21NIC/Lk721mI3Wvfj3k+emWXmmvS5yyq/34ld02cnoC0G+SD50w0ivCL/u4qlyi5NQCCDStfOQGxSda/4dQNlr10ihy92GbwoKkyuBhR93/YEMyCQh6boKDWBh05Ixv1ylMpbKJOyEeKMUu3lSm9T693vMZuMbvDlQyDdLLwbZxmlY1g/e/TqxlyeRHgfbDRsKiZ6md2u/pWuIzlAiMl5+88a23m94tY9IxHyVoYYPnJFLcqqxcNqGHMUscafnyJJyb84R6PRJ3rreB/bvENcuqBRH+cbfiXJdsSEBfaqqN8etu3hLvRYmIy3X3yLiJ5iu3Q+6OE4z+pL9MQI6GMUiYi67GRNdf6VrmODojJ8bCEJzLlQ9BaGm/AGtiu498ckn0Hto56/vWrvGCgBtcBt5qhijj4KkGnqu5SVgYI4WJMJFXS2GWZ8MSoiD69UKkwMVDwwrGuNWz9e3Dtjml4+BtXfLfyr+30dsHB4UjsTu8S7NPB5b/poZBjvoHkyHL1IXROMVcsYQsonqGFRuXXaP64w8EUm6Gj3N9Il6VOEZZCLllONIx5nb7bRKtACteJ6l63RbS6qSGjs6jdPe2fhaoVbIFAw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
